spring:
  application:
    name: BatterySwapStation
  datasource:
    url: jdbc:postgresql://localhost:5432/BatterySwapStationDB
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: localhost
      port: 6379
      connect-timeout: 2000ms
      jedis:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
  task:
    scheduling:
      pool:
        size: 5
      thread-name-prefix: scheduler-


logging:
  level:
    org.springframework.security: debug
    com.swd392.BatterySwapStation: debug
    org.springframework.web: debug

jwt:
  secret: fksldjfuewrujweifdsferwetewqfsrewrtydsfsadgwerokjilgweyhklvjiosdjriowejtfjkweljrklwhrewjklg
  access-token-expiration: 900000
  refresh-token-expiration: 604800000


springdoc:
  swagger-ui:
    url: /v3/api-docs
    config-url: /v3/api-docs/swagger-config
    path: /swagger-ui

  api-docs:
    path: /v3/api-docs

server:
  forward-headers-strategy: framework

vnPay:
  vnp_TmnCode: DFAMVI8U
  vnp_HashSecret: O0HVK10UY0KZ0HDNYGVWO59I6JD67POO
  vnp_Url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
